services:
  app:
    build: .
    image: ghcr.io/baditaflorin/go_services_dashboard:latest
    container_name: go_services_dashboard
    restart: always
    env_file:
      - .env
    network_mode: host
