services:
  app:
    build: .
    image: ghcr.io/baditaflorin/go_services_dashboard:latest
    container_name: go_services_dashboard
    restart: always
    env_file:
      - .env
    ports:
      - "43565:43565"
    networks:
      - pentest_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  pentest_network:
    external: true
